{% set python_min = '3.10' %}
{% set name = "truststore" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/truststore-{{ version }}.tar.gz
  sha256: 5da347c665714fdfbd46f738c823fe9f0d8775e41ac5fb94f325749091187896

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - truststore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sethmlarson/truststore
  summary: Verify certificates using native system trust stores
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
